# Jekyll configuration precedence:
# 1. Gruntfile task
# 2. config.build.yml
# 3. config.yml

name: cebuhomepages
description: Cebu Home Page, helping you buy and sell your property with ease.
author:
  name: ian
  email: hello@iancabigon.me

# Grunt handles images and assets.
exclude: ['images', 'css', 'js', 'fonts',
          '**.png', '**.jpg', '**.jpeg', '**.gif', '**.webp', '**.svg', '**.ico']

include: ['.htaccess']

# _config.build.yml sets future and show_drafts to false on `grunt build`
future: true
show_drafts: true

# Markdown library
markdown: kramdown
#   auto_ids: true
#   footnote_nr: 1
#   entity_output: as_char
#   toc_levels: 1..6
#   use_coderay: false
#   coderay:
#     coderay_wrap: div
#     coderay_line_numbers: inline
#     coderay_line_numbers_start: 1
#     coderay_tab_width: 4
#     coderay_bold_every: 10
#     coderay_css: style

pygments: false

#baseurl: "http://localhost:3000"
baseurl: "https://cebuhomepages.github.io"
cdn: "https://googledrive.com/host/0B3imkbmUgHpnflNkYjhIcElFVm9WVm51VHQ1NEdIb2QwWWcyRFNDSDRUbHViNmdPUDV1Tjg"

owner:
  fullname: Luchelle Ann Cabigon
  nickname: Luchelle
  nickname_short: Luch
  job: Licensed Real Estate Broker
  service: I'm helping you Buy or Sell your property
  address: "Hernan Cortes Street, Casuntingan, Mandaue City, CEBU,PH"
  phone: "+639176312463"
  phone_display: "0917 631 2463"
  email: luchelle@cebuhomepages.com
  site: www.cebuhomepages.com

fbc-comments-firebase: https://chpcomments.firebaseio.com/

logo: /images/logo.jpg

name: Cebu Home Pages
copyright_date: 2015

facebook: https://facebook.com/cebuhomepages
twitter: https://twitter.com/cebuhomepages
google_plus: https://google.com/+Cebuhomepages
